# Generated by Django 3.0.2 on 2020-01-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoTData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'iot_datum',
                'verbose_name_plural': 'iot_data',
                'db_table': 'iot_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
