# Generated by Django 3.0.2 on 2020-01-24 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_data', '0002_auto_20200124_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdata',
            name='box_number',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Invalid BoxNumber', regex='^[A-Z0-9]{4}$')]),
        ),
    ]
